### ISSUE TITLE
Encoding ampersands

### ISSUE THREAD

**Issue by jericahuang** [kostrows/prj-rev-bwfs-dasmoto#2]
https://github.com/kostrows/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L5
https://github.com/kostrows/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L10

Something great about the way Github displays your code for you is it highlights errors in red. You see errors on your ampersands in HTML because they're an entity that should be encoded with `&amp;`. So your HTML would instead have something like
`<title>Dasmoto's Arts &amp; Crafts</title>`
and it will appear exactly the same, but encoding won't throw any errors. :)

Check out this reference for a more in-depth rationale:
https://www.quora.com/Why-should-the-ampersand-character-be-HTML-escaped

**Comment by kostrows** [comment]
Thanks, that makes sense.  I saw the red indicating an error in atom, but didn't make the connection that it needed to be escaped.  I'll make sure to pay attention to that in the future and escape them.
