### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jericahuang** [kostrows/prj-rev-bwfs-dasmoto#5]
Great job recreating the Dasmoto site! It looks exactly like the specification and your code accomplished it very well. Check out the other issues I made for polishing things up! A general suggestion for improvement would be to make your code more readable by indenting properly (which you've done well), adding line breaks between sections, and leaving comments in your code to outline sections or explain a piece of code. You're in a great position to succeed in this program. Keep up the great work! You have a lot to be proud of!

**Comment by kostrows** [comment]
Thanks for all the great feedback.  Looking forward to continuing with the course!
